// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview AI-powered diagnostic suggestion flow for doctors based on patient notes.
 *
 * - suggestDiagnosis - A function that takes patient notes and returns potential diagnosis suggestions.
 * - AIDiagnosticSuggestionsInput - The input type for the suggestDiagnosis function.
 * - AIDiagnosticSuggestionsOutput - The return type for the suggestDiagnosis function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AIDiagnosticSuggestionsInputSchema = z.object({
  patientNotes: z
    .string()
    .describe('Detailed notes about the patient symptoms, medical history, and examination findings.'),
});
export type AIDiagnosticSuggestionsInput = z.infer<typeof AIDiagnosticSuggestionsInputSchema>;

const AIDiagnosticSuggestionsOutputSchema = z.object({
  diagnosisSuggestions: z
    .string()
    .describe('A list of potential diagnosis suggestions based on the patient notes.'),
});
export type AIDiagnosticSuggestionsOutput = z.infer<typeof AIDiagnosticSuggestionsOutputSchema>;

export async function suggestDiagnosis(input: AIDiagnosticSuggestionsInput): Promise<AIDiagnosticSuggestionsOutput> {
  return aiDiagnosticSuggestionsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'aiDiagnosticSuggestionsPrompt',
  input: {schema: AIDiagnosticSuggestionsInputSchema},
  output: {schema: AIDiagnosticSuggestionsOutputSchema},
  prompt: `You are an AI assistant that helps doctors by suggesting potential diagnoses based on patient notes.

  Consider the following patient notes:
  {{patientNotes}}

  Provide a list of potential diagnosis suggestions.`,
});

const aiDiagnosticSuggestionsFlow = ai.defineFlow(
  {
    name: 'aiDiagnosticSuggestionsFlow',
    inputSchema: AIDiagnosticSuggestionsInputSchema,
    outputSchema: AIDiagnosticSuggestionsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
